"------------------
" Main settings
"------------------
set nocompatible
set history=500 " длина истории команд
set undolevels=100 " память отмен
set ttyfast " ???

filetype off

"Pathogen
execute pathogen#infect()
"Vundle
call vundle#rc()

"-----------------
" Bundles
"----------------- 
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'Shougo/neocomplcache'
Bundle 'scrooloose/syntastic'
Bundle 'fholgado/minibufexpl.vim'
Bundle 'majutsushi/tagbar'
Bundle 'tpope/vim-fugitive'
Bundle 'itchyny/lightline.vim'
Bundle 'gmarik/vundle'
Bundle 'Valloric/YouCompleteMe'
Bundle 'nvie/vim-flake8'
Bundle 'flazz/vim-colorschemes'
Bundle 'w0ng/vim-hybrid'
Bundle 'klen/python-mode'
Bundle 'tpope/vim-surround'
Bundle 'fisadev/vim-debug.vim'
Bundle 'fisadev/FixedTaskList.vim'
Bundle 'fisadev/fisa-vim-colorscheme'
Bundle 'majutsushi/tagbar'
Bundle 'rosenfeld/conque-term'
Bundle 'Townk/vim-autoclose'
Bundle 'altercation/vim-colors-solarized.git'
" Snippets manager (SnipMate), dependencies, and snippets repo
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'honza/vim-snippets'
Bundle 'garbas/vim-snipmate'
Bundle 'fisadev/vim-isort'
Bundle 'matchit.zip'
Bundle 'YankRing.vim'

filetype on
filetype plugin indent on

"Color setup
syntax on
if has('gui_running')
    set background=dark
    colorscheme solarized
else
    let g:solarized_termcolors=256
    set background=dark
    colorscheme solarized
endif
highlight Pmenu ctermbg=7 ctermfg=0 guibg=blue
highlight PmenuSel ctermbg=4 ctermfg=7 guibg=blue guifg=white

"Allow delete characters by backspace in insert mode
set backspace=2

"Footer setup
set laststatus=2
set cmdheight=1

"Tab options
set autoindent
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

"Fold defaults
"set foldcolumn=3
set foldmethod=syntax
set foldlevel=99
"set foldmethod=indent
"Useful hints
set showmatch " показывать парные скобки
set ignorecase " в общем случае, поиск без учета регистра
set smartcase " но если есть большие символы - то с учетом регистра
set hlsearch " подсвечивать все найденные куски
set incsearch " искать по мере набора
set nowrap " не рвать строки
set listchars+=precedes:<,extends:> " показывать, когда строка выходит за края экрана
set sidescroll=5
set sidescrolloff=5
set scrolloff=2
set hidden
set autowrite
" set tags+=~/.vim/systags
set mouse=a " с поддержкой мыши
set mousemodel=popup


" NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$']
nmap <silent><F2> <esc>:NERDTreeToggle<CR>
imap <silent><F2> <esc>:NERDTreeToggle<CR>
vmap <silent><F2> <esc>:NERDTreeToggle<CR>
noremap <silent><leader>P :NERDTreeToggle<CR>

" NERDCommenter
let NERDCommentWholeLinesInVMode=1
let NERDRemoveAltComs=1
let NERDSpaceDelims=1
let NERDRemoveExtraSpaces=1
let NERDMapleader='.c'

" neocomplcache



" TagList
"let Tlist_Process_File_Always=1
"let Tlist_Auto_Update=1
"let Tlist_File_Fold_Auto_Close=1
"let Tlist_GainFocus_On_ToggleOpen=1
"let Tlist_Close_On_Select=1
"let Tlist_Use_Right_Window=1
"let Tlist_Display_Tag_Scope=1
"let Tlist_Enable_Fold_Column=0
"let Tlist_Show_Menu=1

" MiniBufExplorer

let g:miniBufExplTabWrap=1
let g:miniBufExplMaxSize=1
let g:miniBufExplorerMoreThanOne=0
let loaded_bufexplorer=1
"let g:bufExplorerDefaultHelp=1
"let g:bufExplorerDetailedHelp=1
"let g:bufExplorerShowDirectories=0
"let g:bufExplorerUseCurrentWindow=0
"let g:bufExplorerSplitBelow=1
"let g:bufExplorerSplitRight=1
"let g:bufExplorerSplitVertical=0
"let g:bufExplorerUseCurrentWindow=1
nmap <silent> <leader>b :MBEToggle<CR>
nmap <silent><F3> <esc>:MBEToggle<cr>
imap <silent><F3> <esc>:MBEToggle<cr>
vmap <silent><F3> <esc>:MBEToggle<cr>


"noremap <silent><leader>t :TlistToggle<CR>

" Fugitive

nmap <silent><F10> <esc>:Gstatus<cr>
imap <silent><F10> <esc>:Gstatus<cr>
vmap <silent><F10> <esc>:Gstatus<cr>
nmap <silent><F11> <esc>:Gcommit<cr>
imap <silent><F11> <esc>:Gcommit<cr>
vmap <silent><F11> <esc>:Gcommit<cr>

"------------------
"Useful keymaps
"------------------
let mapleader = "\\"
"let g:NERDUncomLineMap='<leader>C'
" автодополнение скобок 
"inoremap <silent> {<CR> {<CR>}<Esc>O
"inoremap " ""<left>
"inoremap ( ()<left>

" make
nmap <silent><leader>m :w<CR>:syntax<space>on<CR>:make<CR>

" выход из редактора
" nmap <leader>x :TlistSessionSave session.tags<CR>y<CR>:wqa<CR>
nmap <silent> <leader>x :wa<CR>:TlistSessionSave session.tags<CR>y<CR>:qa<CR>
nmap <silent> <leader>q :qa<CR>

" nmap <silent> <F10> :wqa<CR>
" imap <silent> <F10> <ESC>:wqa<CR>
" map <silent><leader>x :wqa<CR>

noremap <silent> <leader>mb :MarksBrowser<CR>
" noremap <silent> <leader>w :SBufExplorer<CR>
" noremap <silent> <leader>a :Inc<CR>

" noremap <silent> <leader>d :ToggleQuickfix<CR>

nnoremap <silent> <leader>W :set<Space>nowrap!<CR>
nnoremap <silent> <leader>n :set<Space>nu!<CR>
"noremap <silent> <C-h> :set nocursorline<CR>:wincmd h<CR>:set cursorline<CR>
"noremap <silent> <C-j> :set nocursorline<CR>:wincmd j<CR>:set cursorline<CR>
"noremap <silent> <C-k> :set nocursorline<CR>:wincmd k<CR>:set cursorline<CR>
"noremap <silent> <C-l> :set nocursorline<CR>:wincmd l<CR>:set cursorline<CR>

set wildmenu
set wcm=<Tab>
menu Encoding.koi8-r :e ++enc=koi8-r<CR>
menu Encoding.utf-8 :e ++enc=utf8 <CR>
menu Encoding.windows-1251 :e ++enc=cp1251<CR>
menu Encoding.cp866 :e ++enc=cp866<CR>
noremap <silent> <leader>e :emenu Encoding.<TAB>

autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete

"let &errorformat="%Dgmake[%*\\d]:\ Leaving\ directory\ `%f'," . &errorformat
let &errorformat="%f:%l: %t%*[^:]:%m," . &errorformat
